services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_USER=myuser'
      - 'MARIADB_DATABASE=people'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
    ports:
      - '3306'