server:
  servlet:
    context-path: /people-api

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.graphql: DEBUG

spring:
  application:
    name: people

  threads:
    virtual:
      enabled: true

  sql:
    init:
      mode: always
      platform: mariadb

  graphql:
    path: /graphql
    graphiql:
      enabled: true
    schema:
      locations: classpath*:graphql/

  datasource:
    username: myuser
    password: secret
    url: jdbc:mariadb://localhost:3306/people
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect